### ISSUE TITLE
"failed   ! disconnect returned -5" error

### ISSUE THREAD

**Issue by prazsmarid** [Wiznet/RP2040-HAT-AWS-C#4]
Dear developer,
I have tried to compile the **aws_iot_http.c** example but I always get the -5 error at the end.
Here is the log:
`====================================================================================================
W5100S network configuration : DHCP

MAC : 00:08:DC:12:34:56
IP          : 192.168.1.164
Subnet Mask : 255.255.255.0
Gateway     : 192.168.1.1
DNS         : 192.168.1.1
===================================================================================================

 DHCP leased time : 259200 seconds
 failed
  ! disconnect returned -5
`
In the example I have tried these changes but I always got the -5 error.
#define HTTP_GET_URL **"http://wifitest.adafruit.com/testwifi/index.html"**
#define HTTP_GET_URL **"192.168.1.1"**
#define SOCKET_HTTP **0**
#define SOCKET_HTTP **1**
How can I solve the connection problem?
Thanks in advance.

**Comment by Giung951** [comment]
Hello @prazsmarid

There seems to be some problem with the modified code.

```
#define HTTP_GET_URL "http://wifitest.adafruit.com/testwifi/index.html"
#define HTTP_GET_URL "192.168.1.1"
#define SOCKET_HTTP 0
#define SOCKET_HTTP 1
```

Would you like to fix it as below?

![image](https://user-images.githubusercontent.com/53921945/179895272-9d043c4d-9184-4793-8cda-bfdbab0ec574.png)
